class Map:
    # mapping_table = {
    #     # All unique cities from restaurants.city
    #     "city": {'Cedar Rapids/Iowa City', 'Goa', 'Nashik', 'Savannah', 'Faridabad', 'Fernley',
    #              'Mohali', 'Pretoria', 'Coimbatore', 'Augusta', 'Aurangabad', 'Pasay City', 'Rio de Janeiro',
    #              'Phillip Island', 'San Juan City', 'Bhubaneshwar', 'Kochi', 'Dicky Beach', 'Sharjah', 'Colombo',
    #              'Penola', 'Chatham-Kent', 'Patna', 'Puducherry', 'Mc Millan', 'Makati City', 'Winchester Bay',
    #              'Pune', 'Armidale', 'Surat', 'Palm Cove', 'Albany', 'Indore', 'Pocatello', 'Varanasi',
    #              'East Ballina', 'Amritsar', 'Tanunda', 'Johannesburg', 'Vizag', 'Princeton', 'Panchkula',
    #              'Miller', 'Inner City', 'Mayfield', 'Beechworth', 'Victor Harbor', 'Kanpur', 'Potrero',
    #              'Gainesville', 'Dalton', 'Forrest', 'Rest of Hawaii', 'Flaxton', 'Dubuque', 'Athens', 'Lucknow',
    #              'Macon', 'Chennai', 'Orlando', 'Manchester', 'Dubai', 'Guwahati', 'Waterloo', 'Bhopal', 'Boise',
    #              'Dehradun', 'Santa Rosa', 'New Delhi', 'Clatskanie', 'Mangalore', '€¡stanbul', 'Ojo Caliente',
    #              'Cochrane', 'Ranchi', 'Vadodara', 'Lakeview', 'Cape Town', 'Yorkton', 'Ludhiana', 'Quezon City',
    #              'Tangerang', 'Lincoln', 'Hyderabad', 'Valdosta', 'Vineland Station', 'Noida', 'Ahmedabad', 'Sandton',
    #              'Des Moines', 'Pensacola', 'Auckland', 'Trentham East', 'Randburg', 'Pasig City', 'SÌ£o Paulo',
    #              'Mysore', 'Ankara', 'Doha', 'Hepburn Springs', 'Jakarta', 'Allahabad', 'Lorn', 'Mumbai', 'Weirton',
    #              'Edinburgh', 'Tampa Bay', 'Middleton Beach', 'Balingup', 'Montville', 'Taguig City', 'Sioux City',
    #              'Ghaziabad', 'Jaipur', 'Wellington City', 'Lakes Entrance', 'Bangalore', 'Gurgaon', 'Agra',
    #              'Mandaluyong City', 'Singapore', 'Inverloch', 'Birmingham', 'Secunderabad', 'Columbus', 'London',
    #              'Chandigarh', 'Abu Dhabi', 'Nagpur', 'Bogor', 'Bandung', 'Paynesville', 'Kolkata', 'Huskisson', 'Monroe',
    #              'Tagaytay City', 'Macedon', 'Vernonia', 'Consort', 'Davenport', 'BrasÌ_lia'},
    #     # All unique countries from code.country_name
    #     "country": {'India', 'Australia', 'Phillipines', 'Qatar', 'United States', 'Canada', 'Brazil', 'South Africa',
    #                 'Singapore', 'New Zealand', 'Sri Lanka', 'Indonesia', 'Turkey', 'Country', 'United Kingdom', 'UAE'},
    #     # All unique cuisine types from cuisines.cuisine
    #     "cuisine": {'Bar Food', 'Malaysian', 'New American', 'D√å_ner', 'Sandwich', 'Belgian', 'Oriya', 'Coffee and Tea',
    #                 'Hawaiian', 'Bihari', 'Arabian', 'Rajasthani', 'Scottish', 'Mughlai', 'Thai', 'Afghani', 'Armenian',
    #                 'Maharashtrian', 'Malay', 'Greek', 'British', 'Bubble Tea', 'Healthy Food', 'Pizza', 'Durban',
    #                 'Hyderabadi', 'Portuguese', 'Ramen', 'Drinks Only', 'French', 'Gujarati', 'Modern Indian', 'Filipino',
    #                 'Awadhi', 'Mangalorean', 'Asian Fusion', 'Cuisine Varies', 'Chinese', 'Sri Lankan', 'Kerala', 'Southern',
    #                 'Mithai', 'Singaporean', 'Goan', 'German', 'Tibetan', 'Raw Meats', 'Bengali', 'International',
    #                 'Tex-Mex', 'Middle Eastern', 'Desserts', 'Naga', 'Seafood', 'Gourmet Fast Food', 'African', 'Bakery',
    #                 'Fish and Chips', 'Nepalese', 'Steak', 'Irish', 'Sunda', 'Charcoal Grill', 'North Eastern', 'BBQ',
    #                 'World Cuisine', 'Japanese', 'Breakfast', 'Indian', 'Tea', 'North Indian', 'Mineira', 'Spanish', 'Caribbean',
    #                 'Modern Australian', 'Lucknowi', 'Tapas', 'Teriyaki', 'Pakistani', 'Andhra', 'Kebab', 'Mexican', 'Sushi',
    #                 'Mediterranean', 'Izgara', 'Restaurant Cafe', 'Australian', 'Brazilian', 'Southwestern', 'Fusion', 'South Indian',
    #                 'Patisserie', 'Malwani', 'Street Food', 'Moroccan', 'Lebanese', 'European', 'Grill', 'Dim Sum', 'American',
    #                 'Vietnamese', 'Pub Food', 'Chettinad', 'Juices', 'Peranakan', 'Fast Food', 'Turkish', 'Finger Food', 'Diner',
    #                 'Peruvian', 'Kiwi', 'Italian', 'Continental', 'Beverages', 'Burmese', 'Cafe', 'Salad', 'Persian', 'Soul Food',
    #                 'South American', 'Latin American', 'South African', 'Taiwanese', 'Curry', 'Ice Cream', 'Western', 'Indonesian',
    #                 'Cajun', 'Contemporary', 'Vegetarian', 'Cuban', 'Cantonese', 'Canadian', 'Assamese', 'Korean', 'Asian',
    #                 'Turkish Pizza', 'Burger', 'Iranian', 'B√å_rek', 'Deli', 'Parsi', 'Kashmiri', 'Biryani', 'Argentine'},
    #     "rating_text": {'Good', 'Not rated', 'Excellent', 'Average', 'Poor', 'Very Good'},
    #     "currency": {'Dollar($)', 'Indonesian Rupiah(IDR)', 'Sri Lankan Rupee(LKR)', 'Rand(R)', 'Pounds(å£)', 'Emirati Diram(AED)',
    #                 'Qatari Rial(QR)', 'Indian Rupees(Rs.)', 'Turkish Lira(TL)', 'Brazilian Real(R$)', 'NewZealand($)',
    #                 'Botswana Pula(P)'}
    #
    # }
    # mapping_table = {'French': 'cuisine', 'Japanese': 'cuisine', 'Desserts': 'cuisine', 'Seafood': 'cuisine',
    #                  'Asian': 'cuisine', 'Filipino': 'cuisine', 'Indian': 'cuisine', 'Sushi': 'cuisine',
    #                  'Korean': 'cuisine', 'Chinese': 'cuisine', 'European': 'cuisine', 'Mexican': 'cuisine',
    #                  'American': 'cuisine', 'Ice Cream': 'cuisine', 'Cafe': 'cuisine', 'Italian': 'cuisine',
    #                  'Pizza': 'cuisine', 'Bakery': 'cuisine', 'Mediterranean': 'cuisine', 'Fast Food': 'cuisine',
    #                  'Brazilian': 'cuisine', 'Arabian': 'cuisine', 'Bar Food': 'cuisine', 'Grill': 'cuisine',
    #                  'International': 'cuisine', 'Peruvian': 'cuisine', 'Latin American': 'cuisine', 'Burger': 'cuisine',
    #                  'Juices': 'cuisine', 'Healthy Food': 'cuisine', 'Beverages': 'cuisine', 'Lebanese': 'cuisine',
    #                  'Sandwich': 'cuisine', 'Steak': 'cuisine', 'BBQ': 'cuisine', 'Gourmet Fast Food': 'cuisine',
    #                  'Mineira': 'cuisine', 'North Eastern': 'cuisine', '': 'cuisine', 'Coffee and Tea': 'cuisine',
    #                  'Vegetarian': 'cuisine', 'Tapas': 'cuisine', 'Breakfast': 'cuisine', 'Diner': 'cuisine',
    #                  'Southern': 'cuisine', 'Southwestern': 'cuisine', 'Spanish': 'cuisine', 'Argentine': 'cuisine',
    #                  'Caribbean': 'cuisine', 'German': 'cuisine', 'Vietnamese': 'cuisine', 'Thai': 'cuisine',
    #                  'Modern Australian': 'cuisine', 'Teriyaki': 'cuisine', 'Cajun': 'cuisine', 'Canadian': 'cuisine',
    #                  'Tex-Mex': 'cuisine', 'Middle Eastern': 'cuisine', 'Greek': 'cuisine', 'Bubble Tea': 'cuisine',
    #                  'Tea': 'cuisine', 'Australian': 'cuisine', 'Fusion': 'cuisine', 'Cuban': 'cuisine',
    #                  'Hawaiian': 'cuisine', 'Salad': 'cuisine', 'Irish': 'cuisine', 'New American': 'cuisine',
    #                  'Soul Food': 'cuisine', 'Turkish': 'cuisine', 'Pub Food': 'cuisine', 'Persian': 'cuisine',
    #                  'Continental': 'cuisine', 'Singaporean': 'cuisine', 'Malay': 'cuisine', 'Cantonese': 'cuisine',
    #                  'Dim Sum': 'cuisine', 'Western': 'cuisine', 'Finger Food': 'cuisine', 'British': 'cuisine',
    #                  'Deli': 'cuisine', 'Indonesian': 'cuisine', 'North Indian': 'cuisine', 'Mughlai': 'cuisine',
    #                  'Biryani': 'cuisine', 'South Indian': 'cuisine', 'Pakistani': 'cuisine', 'Afghani': 'cuisine',
    #                  'Hyderabadi': 'cuisine', 'Rajasthani': 'cuisine', 'Street Food': 'cuisine', 'Goan': 'cuisine',
    #                  'African': 'cuisine', 'Portuguese': 'cuisine', 'Gujarati': 'cuisine', 'Armenian': 'cuisine',
    #                  'Mithai': 'cuisine', 'Maharashtrian': 'cuisine', 'Modern Indian': 'cuisine',
    #                  'Charcoal Grill': 'cuisine', 'Malaysian': 'cuisine', 'Burmese': 'cuisine', 'Chettinad': 'cuisine',
    #                  'Parsi': 'cuisine', 'Tibetan': 'cuisine', 'Raw Meats': 'cuisine', 'Kerala': 'cuisine',
    #                  'Belgian': 'cuisine', 'Kashmiri': 'cuisine', 'South American': 'cuisine', 'Bengali': 'cuisine',
    #                  'Iranian': 'cuisine', 'Lucknowi': 'cuisine', 'Awadhi': 'cuisine', 'Nepalese': 'cuisine',
    #                  'Drinks Only': 'cuisine', 'Oriya': 'cuisine', 'Bihari': 'cuisine', 'Assamese': 'cuisine',
    #                  'Andhra': 'cuisine', 'Mangalorean': 'cuisine', 'Malwani': 'cuisine', 'Cuisine Varies': 'cuisine',
    #                  'Moroccan': 'cuisine', 'Naga': 'cuisine', 'Sri Lankan': 'cuisine', 'Peranakan': 'cuisine',
    #                  'Sunda': 'cuisine', 'Ramen': 'cuisine', 'Kiwi': 'cuisine', 'Asian Fusion': 'cuisine',
    #                  'Taiwanese': 'cuisine', 'Fish and Chips': 'cuisine', 'Contemporary': 'cuisine', 'Scottish': 'cuisine',
    #                  'Curry': 'cuisine', 'Patisserie': 'cuisine', 'South African': 'cuisine', 'Durban': 'cuisine',
    #                  'Kebab': 'cuisine', 'Turkish Pizza': 'cuisine', 'Izgara': 'cuisine', 'World Cuisine': 'cuisine',
    #                  'D√å_ner': 'cuisine', 'Restaurant Cafe': 'cuisine', 'B√å_rek': 'cuisine', 'Makati City': 'city',
    #                  'Mandaluyong City': 'city', 'Pasay City': 'city', 'Pasig City': 'city', 'Quezon City': 'city',
    #                  'San Juan City': 'city', 'Santa Rosa': 'city', 'Tagaytay City': 'city', 'Taguig City': 'city',
    #                  'BrasÌ_lia': 'city', 'Rio de Janeiro': 'city', 'SÌ£o Paulo': 'city', 'Albany': 'city',
    #                  'Armidale': 'city', 'Athens': 'city', 'Augusta': 'city', 'Balingup': 'city', 'Beechworth': 'city',
    #                  'Boise': 'city', 'Cedar Rapids/Iowa City': 'city', 'Chatham-Kent': 'city', 'Clatskanie': 'city',
    #                  'Cochrane': 'city', 'Columbus': 'city', 'Consort': 'city', 'Dalton': 'city', 'Davenport': 'city',
    #                  'Des Moines': 'city', 'Dicky Beach': 'city', 'Dubuque': 'city', 'East Ballina': 'city',
    #                  'Fernley': 'city', 'Flaxton': 'city', 'Forrest': 'city', 'Gainesville': 'city',
    #                  'Hepburn Springs': 'city', 'Huskisson': 'city', 'Inverloch': 'city', 'Lakes Entrance': 'city',
    #                  'Lakeview': 'city', 'Lincoln': 'city', 'Lorn': 'city', 'Macedon': 'city', 'Macon': 'city',
    #                  'Mayfield': 'city', 'Mc Millan': 'city', 'Middleton Beach': 'city', 'Miller': 'city',
    #                  'Monroe': 'city', 'Montville': 'city', 'Ojo Caliente': 'city', 'Orlando': 'city', 'Palm Cove': 'city',
    #                  'Paynesville': 'city', 'Penola': 'city', 'Pensacola': 'city', 'Phillip Island': 'city',
    #                  'Pocatello': 'city', 'Potrero': 'city', 'Princeton': 'city', 'Rest of Hawaii': 'city', 'Savannah': 'city',
    #                  'Singapore': 'country', 'Sioux City': 'city', 'Tampa Bay': 'city', 'Tanunda': 'city',
    #                  'Trentham East': 'city', 'Valdosta': 'city', 'Vernonia': 'city', 'Victor Harbor': 'city',
    #                  'Vineland Station': 'city', 'Waterloo': 'city', 'Weirton': 'city', 'Winchester Bay': 'city',
    #                  'Yorkton': 'city', 'Abu Dhabi': 'city', 'Dubai': 'city', 'Sharjah': 'city', 'Agra': 'city',
    #                  'Ahmedabad': 'city', 'Allahabad': 'city', 'Amritsar': 'city', 'Aurangabad': 'city', 'Bangalore': 'city',
    #                  'Bhopal': 'city', 'Bhubaneshwar': 'city', 'Chandigarh': 'city', 'Chennai': 'city', 'Coimbatore': 'city',
    #                  'Dehradun': 'city', 'Faridabad': 'city', 'Ghaziabad': 'city', 'Goa': 'city', 'Gurgaon': 'city',
    #                  'Guwahati': 'city', 'Hyderabad': 'city', 'Indore': 'city', 'Jaipur': 'city', 'Kanpur': 'city',
    #                  'Kochi': 'city', 'Kolkata': 'city', 'Lucknow': 'city', 'Ludhiana': 'city', 'Mangalore': 'city',
    #                  'Mohali': 'city', 'Mumbai': 'city', 'Mysore': 'city', 'Nagpur': 'city', 'Nashik': 'city',
    #                  'New Delhi': 'city', 'Noida': 'city', 'Panchkula': 'city', 'Patna': 'city', 'Puducherry': 'city',
    #                  'Pune': 'city', 'Ranchi': 'city', 'Secunderabad': 'city', 'Surat': 'city', 'Vadodara': 'city',
    #                  'Varanasi': 'city', 'Vizag': 'city', 'Bandung': 'city', 'Bogor': 'city', 'Jakarta': 'city',
    #                  'Tangerang': 'city', 'Auckland': 'city', 'Wellington City': 'city', 'Birmingham': 'city',
    #                  'Edinburgh': 'city', 'London': 'city', 'Manchester': 'city', 'Doha': 'city', 'Cape Town': 'city',
    #                  'Inner City': 'city', 'Johannesburg': 'city', 'Pretoria': 'city', 'Randburg': 'city',
    #                  'Sandton': 'city', 'Colombo': 'city', 'Ankara': 'city', '€¡stanbul': 'city', 'India': 'country',
    #                  'Australia': 'country', 'Brazil': 'country', 'Canada': 'country', 'Indonesia': 'country',
    #                  'New Zealand': 'country', 'Phillipines': 'country', 'Qatar': 'country', 'South Africa': 'country',
    #                  'Sri Lanka': 'country', 'Turkey': 'country', 'UAE': 'country', 'United Kingdom': 'country',
    #                  'United States': 'country', 'Excellent': 'rating_text', 'Very Good': 'rating_text', 'Good': 'rating_text',
    #                  'Average': 'rating_text', 'Not rated': 'rating_text', 'Poor': 'rating_text', 'Botswana Pula(P)': 'currency',
    #                  'Brazilian Real(R$)': 'currency', 'Dollar($)': 'currency', 'Emirati Diram(AED)': 'currency',
    #                  'Indian Rupees(Rs.)': 'currency', 'Indonesian Rupiah(IDR)': 'currency', 'NewZealand($)': 'currency',
    #                  'Pounds(å£)': 'currency', 'Qatari Rial(QR)': 'currency', 'Rand(R)': 'currency',
    #                  'Sri Lankan Rupee(LKR)': 'currency', 'Turkish Lira(TL)': 'currency'}
    mapping_table = {'french': 'cuisine', 'japanese': 'cuisine', 'desserts': 'cuisine', 'seafood': 'cuisine',
                     'asian': 'cuisine', 'filipino': 'cuisine', 'indian': 'cuisine', 'sushi': 'cuisine',
                     'korean': 'cuisine', 'chinese': 'cuisine', 'european': 'cuisine', 'mexican': 'cuisine',
                     'american': 'cuisine', 'ice cream': 'cuisine', 'cafe': 'cuisine', 'italian': 'cuisine',
                     'pizza': 'cuisine', 'bakery': 'cuisine', 'mediterranean': 'cuisine', 'fast food': 'cuisine',
                     'brazilian': 'cuisine', 'arabian': 'cuisine', 'bar food': 'cuisine', 'grill': 'cuisine',
                     'international': 'cuisine', 'peruvian': 'cuisine', 'latin american': 'cuisine', 'burger': 'cuisine',
                     'juices': 'cuisine', 'healthy food': 'cuisine', 'beverages': 'cuisine', 'lebanese': 'cuisine',
                     'sandwich': 'cuisine', 'steak': 'cuisine', 'bbq': 'cuisine', 'gourmet fast food': 'cuisine',
                     'mineira': 'cuisine', 'north eastern': 'cuisine', '': 'cuisine', 'coffee and tea': 'cuisine',
                     'vegetarian': 'cuisine', 'tapas': 'cuisine', 'breakfast': 'cuisine', 'diner': 'cuisine',
                     'southern': 'cuisine', 'southwestern': 'cuisine', 'spanish': 'cuisine', 'argentine': 'cuisine',
                     'caribbean': 'cuisine', 'german': 'cuisine', 'vietnamese': 'cuisine', 'thai': 'cuisine',
                     'modern australian': 'cuisine', 'teriyaki': 'cuisine', 'cajun': 'cuisine', 'canadian': 'cuisine',
                     'tex-mex': 'cuisine', 'middle eastern': 'cuisine', 'greek': 'cuisine', 'bubble tea': 'cuisine',
                     'tea': 'cuisine', 'australian': 'cuisine', 'fusion': 'cuisine', 'cuban': 'cuisine',
                     'hawaiian': 'cuisine', 'salad': 'cuisine', 'irish': 'cuisine', 'new american': 'cuisine',
                     'soul food': 'cuisine', 'turkish': 'cuisine', 'pub food': 'cuisine', 'persian': 'cuisine',
                     'continental': 'cuisine', 'singaporean': 'cuisine', 'malay': 'cuisine', 'cantonese': 'cuisine',
                     'dim sum': 'cuisine', 'western': 'cuisine', 'finger food': 'cuisine', 'british': 'cuisine',
                     'deli': 'cuisine', 'indonesian': 'cuisine', 'north indian': 'cuisine', 'mughlai': 'cuisine',
                     'biryani': 'cuisine', 'south indian': 'cuisine', 'pakistani': 'cuisine', 'afghani': 'cuisine',
                     'hyderabadi': 'cuisine', 'rajasthani': 'cuisine', 'street food': 'cuisine', 'goan': 'cuisine',
                     'african': 'cuisine', 'portuguese': 'cuisine', 'gujarati': 'cuisine', 'armenian': 'cuisine',
                     'mithai': 'cuisine', 'maharashtrian': 'cuisine', 'modern indian': 'cuisine',
                     'charcoal grill': 'cuisine', 'malaysian': 'cuisine', 'burmese': 'cuisine', 'chettinad': 'cuisine',
                     'parsi': 'cuisine', 'tibetan': 'cuisine', 'raw meats': 'cuisine', 'kerala': 'cuisine',
                     'belgian': 'cuisine', 'kashmiri': 'cuisine', 'south american': 'cuisine', 'bengali': 'cuisine',
                     'iranian': 'cuisine', 'lucknowi': 'cuisine', 'awadhi': 'cuisine', 'nepalese': 'cuisine',
                     'drinks only': 'cuisine', 'oriya': 'cuisine', 'bihari': 'cuisine', 'assamese': 'cuisine',
                     'andhra': 'cuisine', 'mangalorean': 'cuisine', 'malwani': 'cuisine', 'cuisine varies': 'cuisine',
                     'moroccan': 'cuisine', 'naga': 'cuisine', 'sri lankan': 'cuisine', 'peranakan': 'cuisine',
                     'sunda': 'cuisine', 'ramen': 'cuisine', 'kiwi': 'cuisine', 'asian fusion': 'cuisine',
                     'taiwanese': 'cuisine', 'fish and chips': 'cuisine', 'contemporary': 'cuisine', 'scottish': 'cuisine',
                     'curry': 'cuisine', 'patisserie': 'cuisine', 'south african': 'cuisine', 'durban': 'cuisine',
                     'kebab': 'cuisine', 'turkish pizza': 'cuisine', 'izgara': 'cuisine', 'world cuisine': 'cuisine',
                     'd√å_ner': 'cuisine', 'restaurant cafe': 'cuisine', 'b√å_rek': 'cuisine', 'makati city': 'city',
                     'mandaluyong city': 'city', 'pasay city': 'city', 'pasig city': 'city', 'quezon city': 'city',
                     'san juan city': 'city', 'santa rosa': 'city', 'tagaytay city': 'city', 'taguig city': 'city',
                     'brasì_lia': 'city', 'rio de janeiro': 'city', 'sì£o paulo': 'city', 'albany': 'city',
                     'armidale': 'city', 'athens': 'city', 'augusta': 'city', 'balingup': 'city', 'beechworth': 'city',
                     'boise': 'city', 'cedar rapids/iowa city': 'city', 'chatham-kent': 'city', 'clatskanie': 'city',
                     'cochrane': 'city', 'columbus': 'city', 'consort': 'city', 'dalton': 'city', 'davenport': 'city',
                     'des moines': 'city', 'dicky beach': 'city', 'dubuque': 'city', 'east ballina': 'city',
                     'fernley': 'city', 'flaxton': 'city', 'forrest': 'city', 'gainesville': 'city',
                     'hepburn springs': 'city', 'huskisson': 'city', 'inverloch': 'city', 'lakes entrance': 'city',
                     'lakeview': 'city', 'lincoln': 'city', 'lorn': 'city', 'macedon': 'city', 'macon': 'city',
                     'mayfield': 'city', 'mc millan': 'city', 'middleton beach': 'city', 'miller': 'city', 'monroe': 'city',
                     'montville': 'city', 'ojo caliente': 'city', 'orlando': 'city', 'palm cove': 'city', 'paynesville': 'city',
                     'penola': 'city', 'pensacola': 'city', 'phillip island': 'city', 'pocatello': 'city', 'potrero': 'city',
                     'princeton': 'city', 'rest of hawaii': 'city', 'savannah': 'city', 'singapore': 'country',
                     'sioux city': 'city', 'tampa bay': 'city', 'tanunda': 'city', 'trentham east': 'city', 'valdosta': 'city',
                     'vernonia': 'city', 'victor harbor': 'city', 'vineland station': 'city', 'waterloo': 'city',
                     'weirton': 'city', 'winchester bay': 'city', 'yorkton': 'city', 'abu dhabi': 'city', 'dubai': 'city',
                     'sharjah': 'city', 'agra': 'city', 'ahmedabad': 'city', 'allahabad': 'city', 'amritsar': 'city',
                     'aurangabad': 'city', 'bangalore': 'city', 'bhopal': 'city', 'bhubaneshwar': 'city',
                     'chandigarh': 'city', 'chennai': 'city', 'coimbatore': 'city', 'dehradun': 'city',
                     'faridabad': 'city', 'ghaziabad': 'city', 'goa': 'city', 'gurgaon': 'city', 'guwahati': 'city',
                     'hyderabad': 'city', 'indore': 'city', 'jaipur': 'city', 'kanpur': 'city', 'kochi': 'city',
                     'kolkata': 'city', 'lucknow': 'city', 'ludhiana': 'city', 'mangalore': 'city', 'mohali': 'city',
                     'mumbai': 'city', 'mysore': 'city', 'nagpur': 'city', 'nashik': 'city', 'new delhi': 'city',
                     'noida': 'city', 'panchkula': 'city', 'patna': 'city', 'puducherry': 'city', 'pune': 'city',
                     'ranchi': 'city', 'secunderabad': 'city', 'surat': 'city', 'vadodara': 'city', 'varanasi': 'city',
                     'vizag': 'city', 'bandung': 'city', 'bogor': 'city', 'jakarta': 'city', 'tangerang': 'city',
                     'auckland': 'city', 'wellington city': 'city', 'birmingham': 'city', 'edinburgh': 'city',
                     'london': 'city', 'manchester': 'city', 'doha': 'city', 'cape town': 'city', 'inner city': 'city',
                     'johannesburg': 'city', 'pretoria': 'city', 'randburg': 'city', 'sandton': 'city', 'colombo': 'city',
                     'ankara': 'city', '€¡stanbul': 'city', 'india': 'country', 'australia': 'country', 'brazil': 'country',
                     'canada': 'country', 'indonesia': 'country', 'new zealand': 'country', 'phillipines': 'country',
                     'qatar': 'country', 'south africa': 'country', 'sri lanka': 'country', 'turkey': 'country',
                     'uae': 'country', 'united kingdom': 'country', 'united states': 'country', 'excellent': 'rating_text',
                     'very good': 'rating_text', 'good': 'rating_text', 'average': 'rating_text', 'not rated': 'rating_text',
                     'poor': 'rating_text', 'botswana pula(p)': 'currency', 'brazilian real(r$)': 'currency',
                     'dollar($)': 'currency', 'emirati diram(aed)': 'currency', 'indian rupees(rs.)': 'currency',
                     'indonesian rupiah(idr)': 'currency', 'newzealand($)': 'currency', 'pounds(å£)': 'currency',
                     'qatari rial(qr)': 'currency', 'rand(r)': 'currency', 'sri lankan rupee(lkr)': 'currency',
                     'turkish lira(tl)': 'currency'}

